CREATE TABLE IF NOT EXISTS sellers (
		id INT AUTO_INCREMENT PRIMARY KEY,
		cid VARCHAR(255) NOT NULL UNIQUE,
		company_name VARCHAR(255) NOT NULL,
		address VARCHAR(500) NOT NULL,
		telephone VARCHAR(50) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	)`